package about

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

// export VERSION=`git describe --tags --always`
// export DATE=`date -u '+%Y-%m-%d_%I:%M:%S%p-GMT'`
// export COMMIT_HASH=`git rev-parse HEAD`

var (
	// Version is the version of the program - Git tag - git describe --tags --always
	Version = "v0.0.0"
	// Build is the build number of the program as generated by the CI system
	Build = ""
	// CommitHash is the commit hash of the program - git rev-parse HEAD
	CommitHash = ""
	// Branch is the branch of the program
	Branch = ""
	// Date is the date of the build - date -u '+%Y-%m-%d_%I:%M:%S%p-GMT'
	BuildDate = ""
)

// GetVersion returns the version of the program
func GetVersion(c *gin.Context) {
	c.JSON(http.StatusOK, VersionResponse{
		Version:    Version,
		Build:      Build,
		CommitHash: CommitHash,
		Branch:     Branch,
		BuildDate:  BuildDate,
	})
}

type VersionResponse struct {
	Version    string `json:"version"`
	Build      string `json:"build"`
	CommitHash string `json:"commit_hash"`
	Branch     string `json:"branch"`
	BuildDate  string `json:"build_date"`
}
