name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: sudo go build ./...

#      - name: Install git-lfs
#        run: sudo apt install git-lfs && sudo git lfs install
#
#      - name: Fetch testdata
#        run: sudo git lfs pull
#
#      - name: Extract json file
#        run: sudo go run github.com/feimingxliu/quicksearch/cmd/xmltojson
#
#      - name: Test
#        run: sudo go test -timeout 0 ./...