name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Build frontend
        run: sudo npm install --global yarn
      - run: cd web/web && rm -f yarn.lock && sudo yarn && sudo yarn build

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build Server
        run: sudo go build ./...

#      - name: Install git-lfs
#        run: sudo apt install git-lfs && sudo git lfs install
#
#      - name: Fetch testdata
#        run: sudo git lfs pull
#
#      - name: Extract json file
#        run: sudo go run github.com/feimingxliu/quicksearch/cmd/xmltojson
#
#      - name: Test
#        run: sudo go test -timeout 0 ./...